unzip /home/pi/lptpsettings/lptpsettings.zip

mv /home/pi/lptpsettings/settings.desktop /usr/share/applications/settings.desktop

sudo rm -d -r /home/pi/lptpsettings

echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "

echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                      Succesfuly installed lptpsettings to you'r device!                                                      "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
