mv /home/pi/lptpsettings/settings.desktop /usr/share/applications/settings.desktop

unzip /home/pi/lptpsettings/lptpsettins.zip

echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                      Succesfuly installed lptpsettings to you'r device!                                                      "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
echo "                                                                                                                                                              "
